!define AI_CLIP_MEMORY_HOST_NAME "com.aiclipmemory.bridge"
!define AI_CLIP_MEMORY_MANIFEST_FILE "${AI_CLIP_MEMORY_HOST_NAME}.json"
!define AI_CLIP_MEMORY_HOOK_DIR "${__FILEDIR__}"
!define AI_CLIP_MEMORY_CHROME_KEY "Software\Google\Chrome\NativeMessagingHosts\com.aiclipmemory.bridge"
!define AI_CLIP_MEMORY_EDGE_KEY "Software\Microsoft\Edge\NativeMessagingHosts\com.aiclipmemory.bridge"

!macro AI_CLIP_MEMORY_REMOVE_OWNED_REGISTRATION REGISTRY_KEY
  ReadRegStr $0 HKCU "${REGISTRY_KEY}" ""
  StrCmp $0 "$INSTDIR\${AI_CLIP_MEMORY_MANIFEST_FILE}" 0 +2
  DeleteRegKey HKCU "${REGISTRY_KEY}"
!macroend

!macro NSIS_HOOK_POSTINSTALL
  SetOutPath "$INSTDIR"
  File /a "/oname=${AI_CLIP_MEMORY_MANIFEST_FILE}" "${AI_CLIP_MEMORY_HOOK_DIR}\generated\${AI_CLIP_MEMORY_MANIFEST_FILE}"
  WriteRegStr HKCU "${AI_CLIP_MEMORY_CHROME_KEY}" "" "$INSTDIR\${AI_CLIP_MEMORY_MANIFEST_FILE}"
  WriteRegStr HKCU "${AI_CLIP_MEMORY_EDGE_KEY}" "" "$INSTDIR\${AI_CLIP_MEMORY_MANIFEST_FILE}"
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  !insertmacro AI_CLIP_MEMORY_REMOVE_OWNED_REGISTRATION "${AI_CLIP_MEMORY_CHROME_KEY}"
  !insertmacro AI_CLIP_MEMORY_REMOVE_OWNED_REGISTRATION "${AI_CLIP_MEMORY_EDGE_KEY}"
  Delete "$INSTDIR\${AI_CLIP_MEMORY_MANIFEST_FILE}"
!macroend
